### ISSUE TITLE
bot_d.py

### ISSUE THREAD

**Issue by Xavier129** [EIonTusk/Reddit_Insta_Bot#1]
this showed up in the **log_d.txt** :
[00:39] Successful imported all packages.
[00:39] Successful read of the config_d.ini.
[00:39] ['https:', '', 'i.imgur.com', 'th7A2XW.jpg', '.', 'j', 'p', 'g'] could not downloaded.
[00:39] Unable to find posts. Check if the subreddit name really exists and check the reddit user data.

What's the problem?!
ps: i'm new at everything lmao concerning programming and python stuff

**Comment by EIonTusk** [comment]
There was an issue in my code. I´m sorry for that but i fixed it and it should work now. Just pull this repository again.

**Comment by Xavier129** [comment]
> There was an issue in my code. I´m sorry for that but i fixed it and it should work now. Just pull this repository again.

 [*] Successful imported all packages.
 [*] Successful read of the config_d.ini.
 [*] Start downloading images from reddit
[*] th7A2XW.jpg could not downloaded.
 [*] Unable to find posts. Check if the subreddit name really exists and check the reddit user data. **idk man**

**Comment by EIonTusk** [comment]
You have to create a folder which is called "Pictures_d" so that the programm can store the Images in there.

**Comment by EIonTusk** [comment]
I forgot to create the folder in the repository. I´m really sorry.
