### ISSUE TITLE
bot.py issue

### ISSUE THREAD

**Issue by Xavier129** [EIonTusk/Reddit_Insta_Bot#3]
Idk why this pops up even tho i installed the **autoit** it package !!

> Traceback (most recent call last):
>   File "C:\Users\hp\Desktop\Reddit_Insta_Bot-master\bot.py", line 6, in <module>
>     import autoit
> ModuleNotFoundError: No module named 'autoit'

**Comment by EIonTusk** [comment]
Did you run the install_req.py? It should install autoit and every other package.

**Comment by Xavier129** [comment]
what about this now lmao ?!

> [22:41] th7A2XW.jpg downloaded
> [22:41] 6az7dr5fqsn31.jpg downloaded
> [22:41] i4el1q6ql7841.jpg downloaded
> [22:45] th7A2XW.jpg could not uploaded
> [22:45] 6az7dr5fqsn31.jpg could not uploaded
> [22:45] i4el1q6ql7841.jpg could not uploaded

**why it couldn't be uploaded what's the issue?**

**Comment by EIonTusk** [comment]
Can you post your config.ini pls

**Comment by Xavier129** [comment]
Well i wrote the passwords here with a * but in the config i made the real and correct i have **checked** ,you know !

> [Settings]
> ; number of pictures per subreddit
> number_pics = 3
> 
> ; has to end with a comma
> name_subreddit = dankmemes,
> 
> ; number of upload_dates = number_pics * number of subreddits
> upload_times = 9:00,11:00,13:00,15:00,17:00,22:54
> 
> ; time when the bot should download the pictures from reddit
> download_time = 22:53
> 
> ; text which is shown under your instagram pictures                                          
> text = posted by Reddit_Insta_Bot from EIonTusk
> 
> ; Open in your systemlanguage (written with a capital letter)
> open_language = Open
> 
> ; Path of your Pictures Folder
> path = C:\Users\hp\Desktop\Reddit_Insta_Bot-master\Pictures\
> 
> [Login-Data]
> ; instagram username
> i_username = spicyx.meme
> 
> ; instagram password
> i_password = *
> 
> ; reddit client id
> r_client_id = 0sq7sCu-Mf-hfA
> 
> ; reddit client secret
> r_client_secret = p4-sWWU6WjMWbBuiZDHBzTXQTsI
> 
> ; reddit username
> r_username = MehUs962
> 
> ; reddit password
> r_password = *
>

**Comment by EIonTusk** [comment]
Have you downloaded the __chromedriver.exe__ for your version of chrome?
